T2D-27 First prototype implementation
EBIvariation/amp-t2d-filetracking pull request #1
Opened 2017-03-23 11:28 UTC by poggio84

- Implemented and tested the basic CRUD operations
- Ability to POST a file that will be archived (file system) and stored (tracked) 

T2D-27

2017-03-23 15:43 UTC, cyenyxe requested changes
Several files need code auto-formatting applied.

2017-03-23 15:43 UTC, cyenyxe commented on pom.xml
> +        <version>2.0.0.BUILD-SNAPSHOT</version>
Spring Boot 2.0 is scheduled for a November release. Can we stick to 1.5 for now?

2017-03-23 15:43 UTC, cyenyxe commented on src/main/java/uk/ac/ebi/ampt2d/FileManagerApplication.java
> +	public static void main(String[] args) {
Fix indentation.

2017-03-23 15:43 UTC, cyenyxe commented on src/main/java/uk/ac/ebi/ampt2d/FileType.java
> +public enum FileType {
I guess that for consistency we should drop the `_FILE`.

2017-03-23 15:43 UTC, cyenyxe commented on src/main/java/uk/ac/ebi/ampt2d/controller/FileTrackingController.java
> +    @PostMapping("/upload-and-archive")
I would suggest using just `/upload` so we don't imply any submission-based process.

2017-03-23 15:43 UTC, cyenyxe commented on src/main/java/uk/ac/ebi/ampt2d/controller/FileTrackingController.java
> +
Remove blank line.

2017-03-23 15:43 UTC, cyenyxe commented on src/main/java/uk/ac/ebi/ampt2d/controller/FileTrackingController.java
> +            e.printStackTrace();
If there is an issue the exception should be reported to the user. Can this be done via a `ResponseEntity` object with an HTTP error status?

2017-03-23 15:43 UTC, cyenyxe commented on src/main/java/uk/ac/ebi/ampt2d/controller/FileTrackingController.java
> +        java.io.File convFile = new java.io.File(file.getOriginalFilename());
No need for the absolute package as our `File` class is now `FileMetadata`.

2017-03-23 15:43 UTC, cyenyxe commented on src/main/java/uk/ac/ebi/ampt2d/persistence/entities/FileMetadata.java
> +            e.printStackTrace();
This exception should be raised as the object won't be correct after construction if the hash is null.

2017-03-23 15:43 UTC, cyenyxe commented on src/main/java/uk/ac/ebi/ampt2d/persistence/entities/FileMetadata.java
> +                        long size) {
Fix format, all the parameters should fit in one line.

2017-03-23 15:43 UTC, cyenyxe commented on src/main/java/uk/ac/ebi/ampt2d/persistence/entities/FileMetadata.java
> +        Assert.hasText(hash, "FileMetadata name is required");
I think in this case the message should not refer to `FileMetadata` and the field checked is not correct.

```java
Assert.hasText(name, "File name is required");
```

2017-03-23 15:43 UTC, cyenyxe commented on src/main/java/uk/ac/ebi/ampt2d/persistence/entities/SourceFilePath.java
> +    private FileMetadata fileMetadata;
Could the declaration of entity attributes be consistent across classes? I like the `FileMetadata` structure:

1. Class attributes
2. External references
3. Dates for auditing

2017-03-23 15:43 UTC, cyenyxe commented on src/main/java/uk/ac/ebi/ampt2d/persistence/repository/FileRepositoryCustom.java
> +    Path archive(MultipartFile file);
`upload` would be more applicable to a multipart file.

2017-03-23 15:43 UTC, cyenyxe commented on src/main/java/uk/ac/ebi/ampt2d/persistence/repository/FileRepository.java
> +public interface FileRepository extends PagingAndSortingRepository<FileMetadata, String>, FileRepositoryCustom {
Fix formatting, method declarations should be separate by a blank line. Also applies to `FileRepositoryCustom`.

2017-03-23 15:43 UTC, cyenyxe commented on src/main/java/uk/ac/ebi/ampt2d/storage/FileSystemStorageService.java
> +                throw new StorageException("Failed to store empty file " + file.getOriginalFilename());
The process doesn't really "fail", but it is not permitted. The message should reflect that.

Does this conditional branch need to be inside the try-catch? The [`isEmpty` method Javadoc](http://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/web/multipart/MultipartFile.html#isEmpty--) says nothing about an IOException being thrown.

2017-03-23 15:43 UTC, cyenyxe commented on src/main/java/uk/ac/ebi/ampt2d/storage/FileSystemStorageService.java
> +                throw new StorageFileNotFoundException("Could not read file: " + filename);
Why not just using `FileNotFoundException`?

2017-03-23 15:43 UTC, cyenyxe commented on src/main/resources/application.properties
> +spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL5Dialect
Could this be made compatible with PostgreSQL? That is the production database so it makes sense to use the same in development.

2017-03-23 15:43 UTC, cyenyxe commented on src/main/resources/application.properties
> +
Add a comment about these 2 configuration parameters.

2017-03-23 15:43 UTC, cyenyxe commented on src/test/java/uk/ac/ebi/ampt2d/persistence/repository/FileMetadataRepositoryTest.java
> +        fileRepository.deleteAll();
This must be unnecessary. If we need it then something is wrongly configured.

2017-03-23 15:43 UTC, cyenyxe commented on src/test/java/uk/ac/ebi/ampt2d/persistence/repository/FileMetadataRepositoryTest.java
> +    public void testCRUD() {
Be consistent when naming tests, either they start with "test" or they don't (the convention is to do so).

2017-03-28 10:44 UTC, poggio84 commented on src/main/java/uk/ac/ebi/ampt2d/storage/FileSystemStorageService.java
> +                throw new StorageFileNotFoundException("Could not read file: " + filename);
Probably just to differentiate from the java.io one. The all folder is from [https://github.com/spring-guides/gs-uploading-files/tree/master/complete/src/main/java/hello/storage](url)

2017-03-28 10:53 UTC, poggio84 commented on src/test/java/uk/ac/ebi/ampt2d/persistence/repository/FileMetadataRepositoryTest.java
> +        fileRepository.deleteAll();
The .`init` is creating the root dir where the files will be stored during the upload. The .`deleteAll` is removing the dir and the content to make sure it is starting from fresh. In production we will need to define the path in `StorageProperties` class and remove the init Bean

2017-03-29 08:47 UTC, cyenyxe commented on src/test/java/uk/ac/ebi/ampt2d/persistence/repository/FileMetadataRepositoryTest.java
> +        fileRepository.deleteAll();
Do you mean the current implementation only works for testing? If so please modify it to make it work both for testing and production. We can discuss if necessary.

2017-04-03 11:19 UTC, jorizci requested changes

2017-04-03 11:19 UTC, jorizci commented on src/main/java/uk/ac/ebi/ampt2d/persistence/entities/FileMetadata.java
> +    private Type type;
Are we gonna support null for type? If we don't know the file type shouldn't be OTHER?

2017-04-03 11:19 UTC, jorizci commented on src/main/java/uk/ac/ebi/ampt2d/persistence/entities/FileMetadata.java
> +    public void setHash(String hash) {
Not used method

2017-04-03 11:19 UTC, jorizci commented on src/main/java/uk/ac/ebi/ampt2d/persistence/entities/FileMetadata.java
> +    public Type getType() {
Not used method

2017-04-03 11:19 UTC, jorizci commented on src/main/java/uk/ac/ebi/ampt2d/persistence/entities/FileMetadata.java
> +    public void setType(Type type) {
Not used method

2017-04-03 11:19 UTC, jorizci commented on src/main/java/uk/ac/ebi/ampt2d/persistence/entities/FileMetadata.java
> +    public long getSize() {
Not used method

2017-04-03 11:19 UTC, jorizci commented on src/main/java/uk/ac/ebi/ampt2d/persistence/entities/FileMetadata.java
> +    public void setSize(long size) {
Not used method

2017-04-03 11:19 UTC, jorizci commented on src/main/java/uk/ac/ebi/ampt2d/persistence/entities/FileMetadata.java
> +        Assert.hasText(name, "File name is required");
Validation makes no sense according to declaration.

2017-04-03 11:19 UTC, jorizci commented on src/main/java/uk/ac/ebi/ampt2d/persistence/entities/FileMetadata.java
> +        return sourceFilePaths;
Don't return the internal list, return a unmodifiable collection to avoid future problems.

2017-04-03 11:19 UTC, jorizci commented on src/main/java/uk/ac/ebi/ampt2d/persistence/entities/FileMetadata.java
> +            this.sourceFilePaths = sourceFilePaths;
Don't store directly the collection, add all the items of the collection to your own. Initializate the sourceFilePaths in constructor.

2017-04-03 11:19 UTC, jorizci commented on src/main/java/uk/ac/ebi/ampt2d/persistence/entities/FileMetadata.java
> +    public void setCreatedDate(LocalDateTime createdDate) {
Not used method

2017-04-03 11:19 UTC, jorizci commented on src/main/java/uk/ac/ebi/ampt2d/persistence/entities/FileMetadata.java
> +    public void setLastModifiedDate(LocalDateTime lastModifiedDate) {
Not used method

2017-04-03 11:19 UTC, jorizci commented on src/main/java/uk/ac/ebi/ampt2d/persistence/entities/SourceFilePath.java
> +    public void setPath(String path) {
Not used method

2017-04-03 11:19 UTC, jorizci commented on src/main/java/uk/ac/ebi/ampt2d/persistence/entities/SourceFilePath.java
> +    public LocalDateTime getCreatedDate() {
Not used method

2017-04-03 11:19 UTC, jorizci commented on src/main/java/uk/ac/ebi/ampt2d/persistence/entities/SourceFilePath.java
> +    public void setCreatedDate(LocalDateTime createdDate) {
Not used method

2017-04-03 11:19 UTC, jorizci commented on src/main/java/uk/ac/ebi/ampt2d/persistence/entities/SourceFilePath.java
> +    public LocalDateTime getLastModifiedDate() {
Not used method

2017-04-03 11:19 UTC, jorizci commented on src/main/java/uk/ac/ebi/ampt2d/persistence/entities/SourceFilePath.java
> +    public void setLastModifiedDate(LocalDateTime lastModifiedDate) {
Not used method

2017-04-03 11:19 UTC, jorizci commented on src/main/java/uk/ac/ebi/ampt2d/persistence/entities/SourceFilePath.java
> +    public SourceFilePath() {
If not used, protected

2017-04-03 11:19 UTC, jorizci commented on src/main/java/uk/ac/ebi/ampt2d/persistence/entities/FileMetadata.java
> +    public FileMetadata() {
If not used, protected

2017-04-03 11:19 UTC, jorizci commented on src/main/java/uk/ac/ebi/ampt2d/storage/FileSystemStorageService.java
> +    @Autowired
No longer needed since Spring 4.3 -> [Spring 4.3 announcement](https://spring.io/blog/2016/03/04/core-container-refinements-in-spring-framework-4-3)

2017-04-03 11:19 UTC, jorizci commented on src/main/java/uk/ac/ebi/ampt2d/storage/StorageException.java
> +public class StorageException extends RuntimeException {
Why runtime exception?

2017-04-03 11:19 UTC, jorizci commented on src/main/java/uk/ac/ebi/ampt2d/controller/FileTrackingController.java
> +        FileMetadata fileMetadata = new FileMetadata(storedFile, Type.VCF, multipartFile.getName());
Why don't asume other?

2017-04-03 11:19 UTC, jorizci commented on src/main/java/uk/ac/ebi/ampt2d/Type.java
> +    OTHER
I think a generic BYTE type fits better than "OTHER"

2017-04-11 13:39 UTC, cyenyxe requested changes

2017-04-11 13:39 UTC, cyenyxe commented on pom.xml
> +    <groupId>uk.ac.ebi.eva</groupId>
The groupId in the accessioning service is `uk.ac.ebi.ampt2d`.

2017-04-11 13:39 UTC, cyenyxe commented on pom.xml
> +        </dependency>
We should prioritize PostgreSQL over MySQL.

2017-04-11 13:39 UTC, cyenyxe commented on pom.xml
> +    <repositories>
Do we really need the `repositories` and `pluginRepositories` tags as they are now? The rest of our projects don't seem to use them.

2017-04-11 13:39 UTC, cyenyxe commented on src/main/java/uk/ac/ebi/ampt2d/persistence/entities/FileMetadata.java
> +        this();
The convention is usually the opposite, calling the constructor with more arguments from the one with less.

2017-04-11 13:39 UTC, cyenyxe commented on src/main/java/uk/ac/ebi/ampt2d/persistence/entities/FileMetadata.java
> +    private static final int MAX_FILE_HASH = 128;
`_LENGTH` suffix would clarify what these are.

2017-04-11 13:39 UTC, cyenyxe commented on src/main/java/uk/ac/ebi/ampt2d/persistence/entities/SourceFilePath.java
> +    private static final int MAX_PATH = 1024;
`_LENGTH` suffix would clarify what these are.

2017-04-11 13:39 UTC, cyenyxe commented on src/main/java/uk/ac/ebi/ampt2d/persistence/repository/FileMetadataRepository.java
> +@RepositoryRestResource(collectionResourceRel = "files", path = FileMetadataRepository.REST_REPOSITORY_FILES)
Wouldn't it be simpler to make "/files" explicit as second argument?

2017-04-11 13:39 UTC, cyenyxe commented on src/main/java/uk/ac/ebi/ampt2d/rest/FileTrackingController.java
> +    public ResponseEntity<?> handleFileUpload(@RequestParam("file") MultipartFile multipartFile) throws
`upload` or `uploadFile`? `handle` sounds redundant.

2017-04-11 13:39 UTC, cyenyxe commented on src/main/java/uk/ac/ebi/ampt2d/rest/FileTrackingController.java
> +    @PostMapping(REST_UPLOAD)
As above, why not using the plain string?

2017-04-11 13:39 UTC, cyenyxe commented on src/main/java/uk/ac/ebi/ampt2d/rest/responses/ExceptionError.java
> + * Spring management of exceptions is outside of the control that provides automatic json converters.
Please care about capitalization, specially "REST output message" as the lower case could cause confusion with "rest of the output message".

2017-04-11 13:39 UTC, cyenyxe commented on src/main/java/uk/ac/ebi/ampt2d/rest/ExceptionHandling.java
> +        logger.error("Exception on rest call " + request.getRequestURI(), exception);
REST

2017-04-11 13:39 UTC, cyenyxe commented on src/main/java/uk/ac/ebi/ampt2d/services/FileTrackingService.java
> +    public void addFileToTrackingService(InputStream inputStream) throws StorageException, IOException {
Redundant name `FileTrackingService.addFileToTrackingService` could be just `FileTrackingService.addFile`.

2017-04-11 13:39 UTC, cyenyxe commented on src/main/java/uk/ac/ebi/ampt2d/services/FileTrackingService.java
> +            fileMetadataRepository.save(fileMetadata);
Is there a way to wrap the filesystem and the database operation into a single transaction?

2017-04-11 13:39 UTC, cyenyxe commented on src/main/java/uk/ac/ebi/ampt2d/storage/FileSystemStorageService.java
> +    public void remove(SourceFilePath sourceFilePath) {
`delete`

2017-04-11 13:39 UTC, cyenyxe commented on src/main/java/uk/ac/ebi/ampt2d/storage/StorageProperties.java
> +    private String location = "upload-dir";
Is this a default in case the value is not defined in the properties file?

2017-04-11 13:39 UTC, cyenyxe commented on src/main/resources/application.properties
> +spring.http.multipart.max-file-size=128KB
We are pretty much screwed if we only accept 128KB files :stuck_out_tongue: Can we set a more appropriate default?

2017-04-11 13:39 UTC, cyenyxe commented on src/test/java/uk/ac/ebi/ampt2d/configuration/RestTemplateConfiguration.java
> +public class RestTemplateConfiguration {
What is this needed for?

2017-04-11 13:39 UTC, cyenyxe commented on src/test/java/uk/ac/ebi/ampt2d/persistence/repository/FileMetadataRepositoryTest.java
> +    private void configureTemporalFilePaths() {
"temporary" instead of "temporal"

2017-04-11 13:39 UTC, cyenyxe commented on src/test/java/uk/ac/ebi/ampt2d/FileManagerApplicationTests.java
> +        Assert.assertEquals(HttpStatus.CREATED,result.getStatusCode());
This class uses `Assert.assertXXX` whereas others use `assertXXX` directly.

2017-04-11 13:39 UTC, cyenyxe commented on src/test/java/uk/ac/ebi/ampt2d/persistence/repository/FileMetadataRepositoryTest.java
> +        List<FileMetadata> fileMetadatas = (ArrayList<FileMetadata>) fileMetadataRepository.findAll();
"metadatas" is not a correct plural noun.

2017-04-11 13:45 UTC, jorizci commented on pom.xml
> +    <repositories>
They are their maven repositories for milestone / release candidate versions. We can remove it.

2017-04-11 13:48 UTC, jorizci commented on src/main/java/uk/ac/ebi/ampt2d/persistence/repository/FileMetadataRepository.java
> +@RepositoryRestResource(collectionResourceRel = "files", path = FileMetadataRepository.REST_REPOSITORY_FILES)
This way it can be reused in the tests later.

2017-04-11 13:51 UTC, jorizci commented on src/main/java/uk/ac/ebi/ampt2d/services/FileTrackingService.java
> +            fileMetadataRepository.save(fileMetadata);
This is the only way, the java transactional system only works for databases. There is no simple way to include code for a broken transaction.

2017-04-12 10:56 UTC, jorizci commented on src/test/java/uk/ac/ebi/ampt2d/configuration/RestTemplateConfiguration.java
> +public class RestTemplateConfiguration {
Is required to inject the TestRestTemplate tool.

2017-04-12 11:14 UTC, jorizci commented on src/main/java/uk/ac/ebi/ampt2d/rest/FileTrackingController.java
> +    @PostMapping(REST_UPLOAD)
As above, that way we can use it for the REST tests.

2017-04-12 12:15 UTC, jorizci approved these changes

2017-04-12 14:02 UTC, cyenyxe requested changes

2017-04-12 14:02 UTC, cyenyxe commented on src/test/java/uk/ac/ebi/ampt2d/FileManagerApplicationTests.java
> +        assertEquals(HttpStatus.CREATED,result.getStatusCode());
Agreed offline to make the double upload and double register return the same HTTP code on the second request.

2017-04-28 10:11 UTC, cyenyxe approved these changes

2017-04-28 10:12 UTC, merged